services:
  - type: web
    name: bvb-canteen
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromValue: "" # User to fill in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        fromValue: "" # User to fill in
      - key: CLOUDINARY_API_KEY
        fromValue: "" # User to fill in
      - key: CLOUDINARY_API_SECRET
        fromValue: "" # User to fill in
